#pragma once

#define SPI_DRIVER SPID0
#define SPI_MOSI_PIN GP7
#define SPI_SCK_PIN GP6

#define QUANTUM_PAINTER_DISPLAY_TIMEOUT 60000
#define QUANTUM_PAINTER_SUPPORTS_256_PALETTE TRUE
#define QUANTUM_PAINTER_SUPPORTS_NATIVE_COLORS TRUE
// #define QUANTUM_PAINTER_DEBUG TRUE