// Copyright 2023 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics -i fma.jpg -f pal16`

#pragma once

#include <qp.h>

extern const uint32_t gfx_fma_length;
extern const uint8_t  gfx_fma[9150];
